
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    url: ENC(nMu34VH1h2uWLnyvKEAJcTbB2uSQweNl25+2aJ5bLz2hL5MFlTz+uR4U0vfiivCTbL5KidpCK1+dR5Pj7PWloWWyDtmk0JfT1r3u+o2enovykGT/+cp7gg==)
    username: ENC(3hlhAkL3m3M1lWLhVirHTT3RwgVBRydq)
    password: ENC(LJPXVT7wb+VqEWC9RGl9P1FeO5Hb9HSb)
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
#  h2:
#    console:
#      enabled: true
#    profiles:
#      active: local
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1
#      username: sa
#      password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
  security:
    user:
      name: user
      password: 1234
jwt:
  secretKey: secret
  issuer: ehjeong
  expirationMinute: 10

