
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_PASSWORD}

spring:
  datasource:
    url: ENC(5GEENE/PtRII9RkgwTvd9/uxSjbRiq4kgFq9S1iPMaNimpr6wh7HpZCcPnypssv3voJ2o5Pql4Z2dE+4EnOshm/oRbxSYjdSQGzhweFdXEJcKTyQN6GMgg==)
    username: ENC(dmAJ2s+HEwgp/TcQFaO4KhiK762V6oMl)
    password: ENC(dR9hBIkUg5sh++Zh2xEsV6KudUbtnUk8)
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
#  h2:
#    console:
#      enabled: true
#    profiles:
#      active: local
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1
#      username: sa
#      password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
  security:
    user:
      name: user
      password: 1234
jwt:
  secretKey: secret
  issuer: ehjeong
  expirationMinute: 10

