# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Whistle CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env: 
  S3_BUCKET_NAME: bucket-whistle
  PROJECT_NAME: CI-CD

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x .spring/gradlew
        shell: bash
        
      - name: Build with Gradle
        run: .spring/gradlew build
        shell: bash
        
      - name: Make zip file
        run: zip -r ./Whistle.zip .
        shell: bash
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./Whistle.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/Whistle.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name Whistle-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name Whistle --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/Whistle.zip
        
